language: python
python:
          - '3.6'
branches:
        only:
          - staging

before_script:
          - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

services:
          - postgresql

script:
          - ./manage.py test
